version: "3"

services:
  django:
    build: ./backend
    command: sh -c "python manage.py makemigrations && python manage.py migrate && daphne -e ssl:8000:privateKey=/usr/src/app/django.key:certKey=/usr/src/app/django.crt backend.asgi:application"
    working_dir: /usr/src/app/
    volumes:
      - ./backend:/usr/src/app/
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
    env_file:
      - ./.env
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:14.4-alpine
    volumes:
      - postgres_db:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
    ports:
      - "5432:5432"
  nginx:
    build: ./frontend
    ports:
      - "3000:80"
      - "443:443"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - django
  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_db:
